#!/bin/sh
# Gera internal/api/unimplemented.gen.go: implementação "501" de gen.StrictServerInterface.
# Cada módulo (M1+) sobrepõe os métodos que implementa (métodos do Server sombreiam os embutidos).
set -eu
in=internal/api/gen/api.gen.go
out=internal/api/unimplemented.gen.go
{
  echo "// Code generated by internal/api/gen_unimplemented.sh; DO NOT EDIT."
  echo
  echo "package api"
  echo
  echo 'import ('
  echo '	"context"'
  echo
  echo '	"github.com/cassfrei/vitafamily/apps/api/internal/api/gen"'
  echo '	"github.com/cassfrei/vitafamily/apps/api/internal/platform/httpx"'
  echo ')'
  echo
  echo "// Unimplemented responde 501 a todas as operações do contrato ainda sem módulo."
  echo "type Unimplemented struct{}"
  echo
  echo "var _ gen.StrictServerInterface = Unimplemented{}"
  awk '
    /^type StrictServerInterface interface/ {inb=1; next}
    inb && /^}/ {inb=0}
    inb && /^\t[A-Z][A-Za-z0-9]*\(ctx context.Context, request [A-Za-z0-9]+\) \([A-Za-z0-9]+, error\)$/ {
      name=$1; sub(/\(.*/, "", name)
      req=$0; sub(/.*request /, "", req); sub(/\).*/, "", req)
      resp=$0; sub(/.*\) \(/, "", resp); sub(/,.*/, "", resp)
      printf "\nfunc (Unimplemented) %s(_ context.Context, _ gen.%s) (gen.%s, error) {\n\treturn nil, httpx.ErrNotImplemented\n}\n", name, req, resp
    }' "$in"
} > "$out"
