// Code generated by internal/api/gen_unimplemented.sh; DO NOT EDIT.

package api

import (
	"context"

	"github.com/cassfrei/vitafamily/apps/api/internal/api/gen"
	"github.com/cassfrei/vitafamily/apps/api/internal/platform/httpx"
)

// Unimplemented responde 501 a todas as operações do contrato ainda sem módulo.
type Unimplemented struct{}

var _ gen.StrictServerInterface = Unimplemented{}

func (Unimplemented) AdminListClinics(_ context.Context, _ gen.AdminListClinicsRequestObject) (gen.AdminListClinicsResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) AdminCreateClinic(_ context.Context, _ gen.AdminCreateClinicRequestObject) (gen.AdminCreateClinicResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) AdminUpdateClinic(_ context.Context, _ gen.AdminUpdateClinicRequestObject) (gen.AdminUpdateClinicResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) AdminSetClinicStatus(_ context.Context, _ gen.AdminSetClinicStatusRequestObject) (gen.AdminSetClinicStatusResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) AdminListUsers(_ context.Context, _ gen.AdminListUsersRequestObject) (gen.AdminListUsersResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) AdminReactivateUser(_ context.Context, _ gen.AdminReactivateUserRequestObject) (gen.AdminReactivateUserResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) AdminSuspendUser(_ context.Context, _ gen.AdminSuspendUserRequestObject) (gen.AdminSuspendUserResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ListAlerts(_ context.Context, _ gen.ListAlertsRequestObject) (gen.ListAlertsResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) MarkAllAlertsRead(_ context.Context, _ gen.MarkAllAlertsReadRequestObject) (gen.MarkAllAlertsReadResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) MarkAlertRead(_ context.Context, _ gen.MarkAlertReadRequestObject) (gen.MarkAlertReadResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) Login(_ context.Context, _ gen.LoginRequestObject) (gen.LoginResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) Logout(_ context.Context, _ gen.LogoutRequestObject) (gen.LogoutResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ChangePassword(_ context.Context, _ gen.ChangePasswordRequestObject) (gen.ChangePasswordResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ForgotPassword(_ context.Context, _ gen.ForgotPasswordRequestObject) (gen.ForgotPasswordResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ResetPassword(_ context.Context, _ gen.ResetPasswordRequestObject) (gen.ResetPasswordResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) RefreshToken(_ context.Context, _ gen.RefreshTokenRequestObject) (gen.RefreshTokenResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) Register(_ context.Context, _ gen.RegisterRequestObject) (gen.RegisterResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ResendVerification(_ context.Context, _ gen.ResendVerificationRequestObject) (gen.ResendVerificationResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) VerifyEmail(_ context.Context, _ gen.VerifyEmailRequestObject) (gen.VerifyEmailResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ListFamilies(_ context.Context, _ gen.ListFamiliesRequestObject) (gen.ListFamiliesResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) CreateFamily(_ context.Context, _ gen.CreateFamilyRequestObject) (gen.CreateFamilyResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) DeleteFamily(_ context.Context, _ gen.DeleteFamilyRequestObject) (gen.DeleteFamilyResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) GetFamily(_ context.Context, _ gen.GetFamilyRequestObject) (gen.GetFamilyResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) UpdateFamily(_ context.Context, _ gen.UpdateFamilyRequestObject) (gen.UpdateFamilyResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ListClinics(_ context.Context, _ gen.ListClinicsRequestObject) (gen.ListClinicsResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) CreatePrivateClinic(_ context.Context, _ gen.CreatePrivateClinicRequestObject) (gen.CreatePrivateClinicResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) DeletePrivateClinic(_ context.Context, _ gen.DeletePrivateClinicRequestObject) (gen.DeletePrivateClinicResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) UpdatePrivateClinic(_ context.Context, _ gen.UpdatePrivateClinicRequestObject) (gen.UpdatePrivateClinicResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) SetPrivateClinicStatus(_ context.Context, _ gen.SetPrivateClinicStatusRequestObject) (gen.SetPrivateClinicStatusResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ListInvitations(_ context.Context, _ gen.ListInvitationsRequestObject) (gen.ListInvitationsResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) CreateInvitation(_ context.Context, _ gen.CreateInvitationRequestObject) (gen.CreateInvitationResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) RevokeInvitation(_ context.Context, _ gen.RevokeInvitationRequestObject) (gen.RevokeInvitationResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) LeaveFamily(_ context.Context, _ gen.LeaveFamilyRequestObject) (gen.LeaveFamilyResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ListMembers(_ context.Context, _ gen.ListMembersRequestObject) (gen.ListMembersResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) CreateMember(_ context.Context, _ gen.CreateMemberRequestObject) (gen.CreateMemberResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) RemoveMember(_ context.Context, _ gen.RemoveMemberRequestObject) (gen.RemoveMemberResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) GetMember(_ context.Context, _ gen.GetMemberRequestObject) (gen.GetMemberResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) UpdateMember(_ context.Context, _ gen.UpdateMemberRequestObject) (gen.UpdateMemberResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) CreateDependentAccountInvitation(_ context.Context, _ gen.CreateDependentAccountInvitationRequestObject) (gen.CreateDependentAccountInvitationResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ListAllergies(_ context.Context, _ gen.ListAllergiesRequestObject) (gen.ListAllergiesResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) CreateAllergy(_ context.Context, _ gen.CreateAllergyRequestObject) (gen.CreateAllergyResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) DeleteAllergy(_ context.Context, _ gen.DeleteAllergyRequestObject) (gen.DeleteAllergyResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) UpdateAllergy(_ context.Context, _ gen.UpdateAllergyRequestObject) (gen.UpdateAllergyResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ListAppointments(_ context.Context, _ gen.ListAppointmentsRequestObject) (gen.ListAppointmentsResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) CreateAppointment(_ context.Context, _ gen.CreateAppointmentRequestObject) (gen.CreateAppointmentResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) DeleteAppointment(_ context.Context, _ gen.DeleteAppointmentRequestObject) (gen.DeleteAppointmentResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) GetAppointment(_ context.Context, _ gen.GetAppointmentRequestObject) (gen.GetAppointmentResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) UpdateAppointment(_ context.Context, _ gen.UpdateAppointmentRequestObject) (gen.UpdateAppointmentResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) SetAppointmentStatus(_ context.Context, _ gen.SetAppointmentStatusRequestObject) (gen.SetAppointmentStatusResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) GetBloodType(_ context.Context, _ gen.GetBloodTypeRequestObject) (gen.GetBloodTypeResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) PutBloodType(_ context.Context, _ gen.PutBloodTypeRequestObject) (gen.PutBloodTypeResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ListConditions(_ context.Context, _ gen.ListConditionsRequestObject) (gen.ListConditionsResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) CreateCondition(_ context.Context, _ gen.CreateConditionRequestObject) (gen.CreateConditionResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) DeleteCondition(_ context.Context, _ gen.DeleteConditionRequestObject) (gen.DeleteConditionResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) UpdateCondition(_ context.Context, _ gen.UpdateConditionRequestObject) (gen.UpdateConditionResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) SetDependent(_ context.Context, _ gen.SetDependentRequestObject) (gen.SetDependentResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ListDocuments(_ context.Context, _ gen.ListDocumentsRequestObject) (gen.ListDocumentsResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) UploadDocument(_ context.Context, _ gen.UploadDocumentRequestObject) (gen.UploadDocumentResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) DeleteDocument(_ context.Context, _ gen.DeleteDocumentRequestObject) (gen.DeleteDocumentResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) GetDocument(_ context.Context, _ gen.GetDocumentRequestObject) (gen.GetDocumentResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) DownloadDocument(_ context.Context, _ gen.DownloadDocumentRequestObject) (gen.DownloadDocumentResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ListDoses(_ context.Context, _ gen.ListDosesRequestObject) (gen.ListDosesResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) CorrectDose(_ context.Context, _ gen.CorrectDoseRequestObject) (gen.CorrectDoseResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) MarkDoseNotTaken(_ context.Context, _ gen.MarkDoseNotTakenRequestObject) (gen.MarkDoseNotTakenResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) MarkDoseTaken(_ context.Context, _ gen.MarkDoseTakenRequestObject) (gen.MarkDoseTakenResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ExamResultHistory(_ context.Context, _ gen.ExamResultHistoryRequestObject) (gen.ExamResultHistoryResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ListExaminations(_ context.Context, _ gen.ListExaminationsRequestObject) (gen.ListExaminationsResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) CreateExamination(_ context.Context, _ gen.CreateExaminationRequestObject) (gen.CreateExaminationResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) DeleteExamination(_ context.Context, _ gen.DeleteExaminationRequestObject) (gen.DeleteExaminationResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) GetExamination(_ context.Context, _ gen.GetExaminationRequestObject) (gen.GetExaminationResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) UpdateExamination(_ context.Context, _ gen.UpdateExaminationRequestObject) (gen.UpdateExaminationResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) AddExamResult(_ context.Context, _ gen.AddExamResultRequestObject) (gen.AddExamResultResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) DeleteExamResult(_ context.Context, _ gen.DeleteExamResultRequestObject) (gen.DeleteExamResultResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) UpdateExamResult(_ context.Context, _ gen.UpdateExamResultRequestObject) (gen.UpdateExamResultResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) SetExaminationStatus(_ context.Context, _ gen.SetExaminationStatusRequestObject) (gen.SetExaminationStatusResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) RequestDependentExport(_ context.Context, _ gen.RequestDependentExportRequestObject) (gen.RequestDependentExportResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ListGuardians(_ context.Context, _ gen.ListGuardiansRequestObject) (gen.ListGuardiansResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) AddGuardian(_ context.Context, _ gen.AddGuardianRequestObject) (gen.AddGuardianResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) SetPrimaryGuardian(_ context.Context, _ gen.SetPrimaryGuardianRequestObject) (gen.SetPrimaryGuardianResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) RemoveGuardian(_ context.Context, _ gen.RemoveGuardianRequestObject) (gen.RemoveGuardianResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) MedicationAdherence(_ context.Context, _ gen.MedicationAdherenceRequestObject) (gen.MedicationAdherenceResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ListMedicationPlans(_ context.Context, _ gen.ListMedicationPlansRequestObject) (gen.ListMedicationPlansResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) CreateMedicationPlan(_ context.Context, _ gen.CreateMedicationPlanRequestObject) (gen.CreateMedicationPlanResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) DeleteMedicationPlan(_ context.Context, _ gen.DeleteMedicationPlanRequestObject) (gen.DeleteMedicationPlanResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) GetMedicationPlan(_ context.Context, _ gen.GetMedicationPlanRequestObject) (gen.GetMedicationPlanResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) UpdateMedicationPlan(_ context.Context, _ gen.UpdateMedicationPlanRequestObject) (gen.UpdateMedicationPlanResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) SetMedicationPlanStatus(_ context.Context, _ gen.SetMedicationPlanStatusRequestObject) (gen.SetMedicationPlanStatusResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) ListPrescriptions(_ context.Context, _ gen.ListPrescriptionsRequestObject) (gen.ListPrescriptionsResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) CreatePrescription(_ context.Context, _ gen.CreatePrescriptionRequestObject) (gen.CreatePrescriptionResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) DeletePrescription(_ context.Context, _ gen.DeletePrescriptionRequestObject) (gen.DeletePrescriptionResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) GetPrescription(_ context.Context, _ gen.GetPrescriptionRequestObject) (gen.GetPrescriptionResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) UpdatePrescription(_ context.Context, _ gen.UpdatePrescriptionRequestObject) (gen.UpdatePrescriptionResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) AddPrescriptionMedication(_ context.Context, _ gen.AddPrescriptionMedicationRequestObject) (gen.AddPrescriptionMedicationResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) SetPrescriptionStatus(_ context.Context, _ gen.SetPrescriptionStatusRequestObject) (gen.SetPrescriptionStatusResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) MemberReport(_ context.Context, _ gen.MemberReportRequestObject) (gen.MemberReportResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) SetMemberRole(_ context.Context, _ gen.SetMemberRoleRequestObject) (gen.SetMemberRoleResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) GetSharing(_ context.Context, _ gen.GetSharingRequestObject) (gen.GetSharingResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) PutSharing(_ context.Context, _ gen.PutSharingRequestObject) (gen.PutSharingResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) FamilyReport(_ context.Context, _ gen.FamilyReportRequestObject) (gen.FamilyReportResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) SharedWithMe(_ context.Context, _ gen.SharedWithMeRequestObject) (gen.SharedWithMeResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) HealthLive(_ context.Context, _ gen.HealthLiveRequestObject) (gen.HealthLiveResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) HealthReady(_ context.Context, _ gen.HealthReadyRequestObject) (gen.HealthReadyResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) AcceptInvitation(_ context.Context, _ gen.AcceptInvitationRequestObject) (gen.AcceptInvitationResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) LookupInvitation(_ context.Context, _ gen.LookupInvitationRequestObject) (gen.LookupInvitationResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) DeleteMe(_ context.Context, _ gen.DeleteMeRequestObject) (gen.DeleteMeResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) GetMe(_ context.Context, _ gen.GetMeRequestObject) (gen.GetMeResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) UpdateMe(_ context.Context, _ gen.UpdateMeRequestObject) (gen.UpdateMeResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) RequestMyExport(_ context.Context, _ gen.RequestMyExportRequestObject) (gen.RequestMyExportResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) GetMyExport(_ context.Context, _ gen.GetMyExportRequestObject) (gen.GetMyExportResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) DownloadMyExport(_ context.Context, _ gen.DownloadMyExportRequestObject) (gen.DownloadMyExportResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) GetNotificationPreferences(_ context.Context, _ gen.GetNotificationPreferencesRequestObject) (gen.GetNotificationPreferencesResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) PutNotificationPreferences(_ context.Context, _ gen.PutNotificationPreferencesRequestObject) (gen.PutNotificationPreferencesResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) AddPushSubscription(_ context.Context, _ gen.AddPushSubscriptionRequestObject) (gen.AddPushSubscriptionResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) DeletePushSubscription(_ context.Context, _ gen.DeletePushSubscriptionRequestObject) (gen.DeletePushSubscriptionResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}

func (Unimplemented) AcceptTerms(_ context.Context, _ gen.AcceptTermsRequestObject) (gen.AcceptTermsResponseObject, error) {
	return nil, httpx.ErrNotImplemented
}
