// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"
)

type ActorType string

const (
	ActorTypeUSER          ActorType = "USER"
	ActorTypeSYSTEM        ActorType = "SYSTEM"
	ActorTypePLATFORMADMIN ActorType = "PLATFORM_ADMIN"
)

func (e *ActorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActorType(s)
	case string:
		*e = ActorType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActorType: %T", src)
	}
	return nil
}

type NullActorType struct {
	ActorType ActorType
	Valid     bool // Valid is true if ActorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActorType) Scan(value interface{}) error {
	if value == nil {
		ns.ActorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActorType), nil
}

type AlertSource string

const (
	AlertSourceDOSE        AlertSource = "DOSE"
	AlertSourceAPPOINTMENT AlertSource = "APPOINTMENT"
	AlertSourceEXAMINATION AlertSource = "EXAMINATION"
)

func (e *AlertSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertSource(s)
	case string:
		*e = AlertSource(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertSource: %T", src)
	}
	return nil
}

type NullAlertSource struct {
	AlertSource AlertSource
	Valid       bool // Valid is true if AlertSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertSource) Scan(value interface{}) error {
	if value == nil {
		ns.AlertSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertSource), nil
}

type AlertType string

const (
	AlertTypeMEDICATIONDUE             AlertType = "MEDICATION_DUE"
	AlertTypeAPPOINTMENTREMINDER       AlertType = "APPOINTMENT_REMINDER"
	AlertTypeEXAMREMINDER              AlertType = "EXAM_REMINDER"
	AlertTypeAPPOINTMENTOUTCOMEREQUEST AlertType = "APPOINTMENT_OUTCOME_REQUEST"
)

func (e *AlertType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertType(s)
	case string:
		*e = AlertType(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertType: %T", src)
	}
	return nil
}

type NullAlertType struct {
	AlertType AlertType
	Valid     bool // Valid is true if AlertType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertType) Scan(value interface{}) error {
	if value == nil {
		ns.AlertType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertType), nil
}

type AppointmentStatus string

const (
	AppointmentStatusSCHEDULED AppointmentStatus = "SCHEDULED"
	AppointmentStatusCOMPLETED AppointmentStatus = "COMPLETED"
	AppointmentStatusNOSHOW    AppointmentStatus = "NO_SHOW"
	AppointmentStatusCANCELLED AppointmentStatus = "CANCELLED"
)

func (e *AppointmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppointmentStatus(s)
	case string:
		*e = AppointmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppointmentStatus: %T", src)
	}
	return nil
}

type NullAppointmentStatus struct {
	AppointmentStatus AppointmentStatus
	Valid             bool // Valid is true if AppointmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppointmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppointmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppointmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppointmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppointmentStatus), nil
}

type AuditResult string

const (
	AuditResultSUCCESS AuditResult = "SUCCESS"
	AuditResultDENIED  AuditResult = "DENIED"
	AuditResultFAILURE AuditResult = "FAILURE"
)

func (e *AuditResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditResult(s)
	case string:
		*e = AuditResult(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditResult: %T", src)
	}
	return nil
}

type NullAuditResult struct {
	AuditResult AuditResult
	Valid       bool // Valid is true if AuditResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditResult) Scan(value interface{}) error {
	if value == nil {
		ns.AuditResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditResult), nil
}

type AuthTokenType string

const (
	AuthTokenTypeEMAILVERIFICATION AuthTokenType = "EMAIL_VERIFICATION"
	AuthTokenTypePASSWORDRESET     AuthTokenType = "PASSWORD_RESET"
)

func (e *AuthTokenType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthTokenType(s)
	case string:
		*e = AuthTokenType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthTokenType: %T", src)
	}
	return nil
}

type NullAuthTokenType struct {
	AuthTokenType AuthTokenType
	Valid         bool // Valid is true if AuthTokenType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthTokenType) Scan(value interface{}) error {
	if value == nil {
		ns.AuthTokenType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthTokenType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthTokenType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthTokenType), nil
}

type BloodType string

const (
	BloodTypeAPOS    BloodType = "A_POS"
	BloodTypeANEG    BloodType = "A_NEG"
	BloodTypeBPOS    BloodType = "B_POS"
	BloodTypeBNEG    BloodType = "B_NEG"
	BloodTypeABPOS   BloodType = "AB_POS"
	BloodTypeABNEG   BloodType = "AB_NEG"
	BloodTypeOPOS    BloodType = "O_POS"
	BloodTypeONEG    BloodType = "O_NEG"
	BloodTypeUNKNOWN BloodType = "UNKNOWN"
)

func (e *BloodType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BloodType(s)
	case string:
		*e = BloodType(s)
	default:
		return fmt.Errorf("unsupported scan type for BloodType: %T", src)
	}
	return nil
}

type NullBloodType struct {
	BloodType BloodType
	Valid     bool // Valid is true if BloodType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBloodType) Scan(value interface{}) error {
	if value == nil {
		ns.BloodType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BloodType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBloodType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BloodType), nil
}

type Channel string

const (
	ChannelPUSH  Channel = "PUSH"
	ChannelEMAIL Channel = "EMAIL"
)

func (e *Channel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Channel(s)
	case string:
		*e = Channel(s)
	default:
		return fmt.Errorf("unsupported scan type for Channel: %T", src)
	}
	return nil
}

type NullChannel struct {
	Channel Channel
	Valid   bool // Valid is true if Channel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChannel) Scan(value interface{}) error {
	if value == nil {
		ns.Channel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Channel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Channel), nil
}

type ClinicStatus string

const (
	ClinicStatusACTIVE   ClinicStatus = "ACTIVE"
	ClinicStatusARCHIVED ClinicStatus = "ARCHIVED"
)

func (e *ClinicStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClinicStatus(s)
	case string:
		*e = ClinicStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ClinicStatus: %T", src)
	}
	return nil
}

type NullClinicStatus struct {
	ClinicStatus ClinicStatus
	Valid        bool // Valid is true if ClinicStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClinicStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ClinicStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClinicStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClinicStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClinicStatus), nil
}

type ClinicType string

const (
	ClinicTypePARTNER ClinicType = "PARTNER"
	ClinicTypePRIVATE ClinicType = "PRIVATE"
)

func (e *ClinicType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClinicType(s)
	case string:
		*e = ClinicType(s)
	default:
		return fmt.Errorf("unsupported scan type for ClinicType: %T", src)
	}
	return nil
}

type NullClinicType struct {
	ClinicType ClinicType
	Valid      bool // Valid is true if ClinicType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClinicType) Scan(value interface{}) error {
	if value == nil {
		ns.ClinicType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClinicType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClinicType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClinicType), nil
}

type ConditionKind string

const (
	ConditionKindCONDITION ConditionKind = "CONDITION"
	ConditionKindHISTORY   ConditionKind = "HISTORY"
)

func (e *ConditionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConditionKind(s)
	case string:
		*e = ConditionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ConditionKind: %T", src)
	}
	return nil
}

type NullConditionKind struct {
	ConditionKind ConditionKind
	Valid         bool // Valid is true if ConditionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConditionKind) Scan(value interface{}) error {
	if value == nil {
		ns.ConditionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConditionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConditionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConditionKind), nil
}

type DataCategory string

const (
	DataCategoryALLERGIES    DataCategory = "ALLERGIES"
	DataCategoryCONDITIONS   DataCategory = "CONDITIONS"
	DataCategoryMEDICATION   DataCategory = "MEDICATION"
	DataCategoryAPPOINTMENTS DataCategory = "APPOINTMENTS"
	DataCategoryEXAMS        DataCategory = "EXAMS"
)

func (e *DataCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DataCategory(s)
	case string:
		*e = DataCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for DataCategory: %T", src)
	}
	return nil
}

type NullDataCategory struct {
	DataCategory DataCategory
	Valid        bool // Valid is true if DataCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDataCategory) Scan(value interface{}) error {
	if value == nil {
		ns.DataCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DataCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDataCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DataCategory), nil
}

type DoseStatus string

const (
	DoseStatusPENDING     DoseStatus = "PENDING"
	DoseStatusTAKEN       DoseStatus = "TAKEN"
	DoseStatusNOTTAKEN    DoseStatus = "NOT_TAKEN"
	DoseStatusUNCONFIRMED DoseStatus = "UNCONFIRMED"
)

func (e *DoseStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DoseStatus(s)
	case string:
		*e = DoseStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DoseStatus: %T", src)
	}
	return nil
}

type NullDoseStatus struct {
	DoseStatus DoseStatus
	Valid      bool // Valid is true if DoseStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDoseStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DoseStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DoseStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDoseStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DoseStatus), nil
}

type ExamStatus string

const (
	ExamStatusSCHEDULED ExamStatus = "SCHEDULED"
	ExamStatusCOMPLETED ExamStatus = "COMPLETED"
	ExamStatusCANCELLED ExamStatus = "CANCELLED"
)

func (e *ExamStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExamStatus(s)
	case string:
		*e = ExamStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ExamStatus: %T", src)
	}
	return nil
}

type NullExamStatus struct {
	ExamStatus ExamStatus
	Valid      bool // Valid is true if ExamStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExamStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ExamStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExamStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExamStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExamStatus), nil
}

type ExportReason string

const (
	ExportReasonUSERREQUEST    ExportReason = "USER_REQUEST"
	ExportReasonLEAVEFAMILY    ExportReason = "LEAVE_FAMILY"
	ExportReasonREMOVEDBYADMIN ExportReason = "REMOVED_BY_ADMIN"
)

func (e *ExportReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExportReason(s)
	case string:
		*e = ExportReason(s)
	default:
		return fmt.Errorf("unsupported scan type for ExportReason: %T", src)
	}
	return nil
}

type NullExportReason struct {
	ExportReason ExportReason
	Valid        bool // Valid is true if ExportReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExportReason) Scan(value interface{}) error {
	if value == nil {
		ns.ExportReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExportReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExportReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExportReason), nil
}

type ExportStatus string

const (
	ExportStatusPENDING ExportStatus = "PENDING"
	ExportStatusREADY   ExportStatus = "READY"
	ExportStatusEXPIRED ExportStatus = "EXPIRED"
	ExportStatusFAILED  ExportStatus = "FAILED"
)

func (e *ExportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExportStatus(s)
	case string:
		*e = ExportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ExportStatus: %T", src)
	}
	return nil
}

type NullExportStatus struct {
	ExportStatus ExportStatus
	Valid        bool // Valid is true if ExportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ExportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExportStatus), nil
}

type FamilyRole string

const (
	FamilyRoleFAMILYADMIN  FamilyRole = "FAMILY_ADMIN"
	FamilyRoleFAMILYMEMBER FamilyRole = "FAMILY_MEMBER"
)

func (e *FamilyRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FamilyRole(s)
	case string:
		*e = FamilyRole(s)
	default:
		return fmt.Errorf("unsupported scan type for FamilyRole: %T", src)
	}
	return nil
}

type NullFamilyRole struct {
	FamilyRole FamilyRole
	Valid      bool // Valid is true if FamilyRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFamilyRole) Scan(value interface{}) error {
	if value == nil {
		ns.FamilyRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FamilyRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFamilyRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FamilyRole), nil
}

type InvitationStatus string

const (
	InvitationStatusPENDING  InvitationStatus = "PENDING"
	InvitationStatusACCEPTED InvitationStatus = "ACCEPTED"
	InvitationStatusREVOKED  InvitationStatus = "REVOKED"
	InvitationStatusEXPIRED  InvitationStatus = "EXPIRED"
)

func (e *InvitationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvitationStatus(s)
	case string:
		*e = InvitationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvitationStatus: %T", src)
	}
	return nil
}

type NullInvitationStatus struct {
	InvitationStatus InvitationStatus
	Valid            bool // Valid is true if InvitationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvitationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvitationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvitationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvitationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvitationStatus), nil
}

type InvitationType string

const (
	InvitationTypeMEMBER           InvitationType = "MEMBER"
	InvitationTypeDEPENDENTACCOUNT InvitationType = "DEPENDENT_ACCOUNT"
)

func (e *InvitationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvitationType(s)
	case string:
		*e = InvitationType(s)
	default:
		return fmt.Errorf("unsupported scan type for InvitationType: %T", src)
	}
	return nil
}

type NullInvitationType struct {
	InvitationType InvitationType
	Valid          bool // Valid is true if InvitationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvitationType) Scan(value interface{}) error {
	if value == nil {
		ns.InvitationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvitationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvitationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvitationType), nil
}

type MemberStatus string

const (
	MemberStatusACTIVE  MemberStatus = "ACTIVE"
	MemberStatusBLOCKED MemberStatus = "BLOCKED"
)

func (e *MemberStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberStatus(s)
	case string:
		*e = MemberStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberStatus: %T", src)
	}
	return nil
}

type NullMemberStatus struct {
	MemberStatus MemberStatus
	Valid        bool // Valid is true if MemberStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MemberStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberStatus), nil
}

type NotificationStatus string

const (
	NotificationStatusPENDING NotificationStatus = "PENDING"
	NotificationStatusSENT    NotificationStatus = "SENT"
	NotificationStatusFAILED  NotificationStatus = "FAILED"
	NotificationStatusSKIPPED NotificationStatus = "SKIPPED"
)

func (e *NotificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationStatus(s)
	case string:
		*e = NotificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationStatus: %T", src)
	}
	return nil
}

type NullNotificationStatus struct {
	NotificationStatus NotificationStatus
	Valid              bool // Valid is true if NotificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationStatus), nil
}

type PlanStatus string

const (
	PlanStatusACTIVE PlanStatus = "ACTIVE"
	PlanStatusENDED  PlanStatus = "ENDED"
)

func (e *PlanStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlanStatus(s)
	case string:
		*e = PlanStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PlanStatus: %T", src)
	}
	return nil
}

type NullPlanStatus struct {
	PlanStatus PlanStatus
	Valid      bool // Valid is true if PlanStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlanStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PlanStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlanStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlanStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlanStatus), nil
}

type PlatformRole string

const (
	PlatformRoleNONE          PlatformRole = "NONE"
	PlatformRolePLATFORMADMIN PlatformRole = "PLATFORM_ADMIN"
)

func (e *PlatformRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlatformRole(s)
	case string:
		*e = PlatformRole(s)
	default:
		return fmt.Errorf("unsupported scan type for PlatformRole: %T", src)
	}
	return nil
}

type NullPlatformRole struct {
	PlatformRole PlatformRole
	Valid        bool // Valid is true if PlatformRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlatformRole) Scan(value interface{}) error {
	if value == nil {
		ns.PlatformRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlatformRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlatformRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlatformRole), nil
}

type PrescriptionStatus string

const (
	PrescriptionStatusACTIVE    PrescriptionStatus = "ACTIVE"
	PrescriptionStatusCOMPLETED PrescriptionStatus = "COMPLETED"
	PrescriptionStatusCANCELLED PrescriptionStatus = "CANCELLED"
)

func (e *PrescriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrescriptionStatus(s)
	case string:
		*e = PrescriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PrescriptionStatus: %T", src)
	}
	return nil
}

type NullPrescriptionStatus struct {
	PrescriptionStatus PrescriptionStatus
	Valid              bool // Valid is true if PrescriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrescriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PrescriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrescriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrescriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrescriptionStatus), nil
}

type ScanStatus string

const (
	ScanStatusPENDING  ScanStatus = "PENDING"
	ScanStatusCLEAN    ScanStatus = "CLEAN"
	ScanStatusINFECTED ScanStatus = "INFECTED"
)

func (e *ScanStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScanStatus(s)
	case string:
		*e = ScanStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ScanStatus: %T", src)
	}
	return nil
}

type NullScanStatus struct {
	ScanStatus ScanStatus
	Valid      bool // Valid is true if ScanStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScanStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ScanStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScanStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScanStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScanStatus), nil
}

type ScheduleType string

const (
	ScheduleTypeFIXEDTIMES ScheduleType = "FIXED_TIMES"
	ScheduleTypeINTERVAL   ScheduleType = "INTERVAL"
)

func (e *ScheduleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScheduleType(s)
	case string:
		*e = ScheduleType(s)
	default:
		return fmt.Errorf("unsupported scan type for ScheduleType: %T", src)
	}
	return nil
}

type NullScheduleType struct {
	ScheduleType ScheduleType
	Valid        bool // Valid is true if ScheduleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScheduleType) Scan(value interface{}) error {
	if value == nil {
		ns.ScheduleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScheduleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScheduleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScheduleType), nil
}

type UserStatus string

const (
	UserStatusPENDINGVERIFICATION UserStatus = "PENDING_VERIFICATION"
	UserStatusACTIVE              UserStatus = "ACTIVE"
	UserStatusSUSPENDED           UserStatus = "SUSPENDED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}
