// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package sqlcgen

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1::int AS ok
`

// Verificação de ligação (readiness). Queries de negócio vivem em db/queries/<modulo>.sql.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
